/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 703f33ebf887580241653069bbe065a5)
interface __BaseEnv_Env {
	MESAS: KVNamespace;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
