/* O baralho MUJO (無常) — 28 lâminas. qualidade: sorte 幸 | azar 厄 | reves 転 */
(function () {
  function L(slug, jp, qualidade, nomePt, nomeEn, pt, en) {
    return {
      slug: slug, img: "assets/" + slug + ".webp", jp: jp, qualidade: qualidade,
      nome: { pt: nomePt, en: nomeEn }, leitura: { pt: pt, en: en }
    };
  }
  window.AVDeck = [
    L("mao-esqueletica", "骨の手", "azar", "A Mão Esquelética", "The Skeletal Hand",
      "O que a morte segura não se desapega: toda posse é, no fim, uma questão de tempo.",
      "What death holds, it does not release: all possession is, in the end, a matter of time."),
    L("caveira-derretida", "溶ける髑髏", "azar", "A Caveira Derretida", "The Melting Skull",
      "Até o osso, que jurávamos definitivo, escorre. Nada testemunha para sempre.",
      "Even bone, which we swore was final, runs. Nothing bears witness forever."),
    L("mariposa-da-alma", "魂の蛾", "reves", "A Mariposa da Alma", "The Soul Moth",
      "A alma em trânsito não teme a chama; ela a confunde com a porta.",
      "The soul in transit does not fear the flame; it mistakes it for the door."),
    L("namakubi", "生首", "azar", "Namakubi", "Namakubi",
      "A cabeça cortada dos romances de guerreiros: a justiça que se faz à espada não recorre.",
      "The severed head of warrior tales: justice done by the sword admits no appeal."),
    L("aoandon", "青行燈", "azar", "Aoandon, a Lanterna Azul", "Aoandon, the Blue Lantern",
      "Quando se apaga a centésima vela, ela chega. O fim de toda boa narração é um encontro.",
      "When the hundredth candle goes out, she arrives. The end of every good telling is an encounter."),
    L("chochin", "提灯", "sorte", "O Chochin", "The Paper Lantern",
      "A luz de papel não expulsa a noite; ensina a andar com ela.",
      "Paper light does not banish the night; it teaches you to walk with it."),
    L("bakuto", "博徒", "reves", "O Bakuto", "The Gambler",
      "O jogador profissional sabe o que o jurista esquece: a regra é sempre de quem banca a mesa.",
      "The professional gambler knows what the jurist forgets: the house always writes the rules."),
    L("jigoku", "地獄", "azar", "Jigoku", "Jigoku",
      "O inferno japonês tem burocracia: cada falta registrada, cada pena com artigo.",
      "The Japanese hell has a bureaucracy: every fault on record, every sentence with its article."),
    L("inoshikacho", "猪鹿蝶", "sorte", "Inoshikachō", "Inoshikachō",
      "Javali, veado e borboleta: a trinca que vira o jogo. Até o acaso, às vezes, faz justiça.",
      "Boar, deer and butterfly: the hand that turns the game. Even chance, sometimes, does justice."),
    L("torre-de-raijin", "雷電の塔", "azar", "A Torre de Raijin", "The Tower of Raijin",
      "O trovão não pede licença. Há decisões que caem como o raio: súbitas e sem recurso.",
      "Thunder asks no leave. Some rulings fall like lightning: sudden and without appeal."),
    L("tsukimi", "月見", "sorte", "Tsukimi, a Vigília da Lua", "Tsukimi, the Moon Viewing",
      "Sentar-se para ver a lua é o contrário do processo: um rito que não pede resultado.",
      "Sitting to watch the moon is the opposite of litigation: a rite that asks for no outcome."),
    L("chomurasaki", "紫蝶", "sorte", "Chōmurasaki, a Borboleta Roxa", "Chōmurasaki, the Purple Butterfly",
      "A borboleta que volta é saudade que aceitou a forma de bicho. Sorte é saber recebê-la.",
      "The butterfly that returns is longing in animal form. Luck is knowing how to receive it."),
    L("sapo-do-tofu", "豆腐蛙", "reves", "O Sapo do Tofu", "The Tofu Frog",
      "Carrega tofu numa folha e finge seriedade. Todo tribunal tem o seu dia de farsa.",
      "It carries tofu on a leaf and feigns solemnity. Every court has its day of farce."),
    L("caveira-e-crisantemo", "髑髏と菊", "reves", "A Caveira e o Crisântemo", "The Skull and the Chrysanthemum",
      "A morte e a longevidade no mesmo vaso. Depende do ângulo: epitáfio ou buquê.",
      "Death and longevity in the same vase. It depends on the angle: epitaph or bouquet."),
    L("katana-893", "八九三の刀", "azar", "A Katana 893", "The 893 Katana",
      "O número que não se diz em voz alta. Há códigos mais antigos que a lei, e menos escritos.",
      "The number not said aloud. There are codes older than law, and far less written."),
    L("leque-de-chama", "炎の団扇", "reves", "O Leque de Chama", "The Flame Fan",
      "O leque que atiça o fogo não escolhe o que queima. Instrumento é inocente até a direção.",
      "The fan that feeds the fire does not choose what burns. An instrument is innocent until aimed."),
    L("gashadokuro", "がしゃどくろ", "azar", "Gashadokuro", "Gashadokuro",
      "O esqueleto gigante dos que morreram sem enterro: a injustiça acumulada também se levanta.",
      "The giant skeleton of the unburied dead: accumulated injustice also rises."),
    L("yamabushi", "山伏", "reves", "O Yamabushi", "The Yamabushi Fool",
      "O louco das montanhas desce sem mapa. Todo começo é uma forma educada de vertigem.",
      "The mountain fool descends without a map. Every beginning is a polite form of vertigo."),
    L("centesima-chama", "百目の炎", "azar", "A Centésima Chama", "The Hundredth Flame",
      "Apagar cem velas é convidar o escuro a falar. Há rituais que não deviam terminar.",
      "Snuffing a hundred flames invites the dark to speak. Some rituals should never end."),
    L("danca-de-ikkyu", "一休の踊り", "sorte", "A Dança de Ikkyū", "The Dance of Ikkyū",
      "O monge que dança no velório entendeu antes de todos: a impermanência é também alívio.",
      "The monk who dances at the wake understood first: impermanence is also relief."),
    L("kitsunebi", "狐火", "reves", "Kitsunebi, o Fogo da Raposa", "Kitsunebi, the Fox Fire",
      "A luz que guia para fora da trilha. Nem toda prova ilumina; algumas seduzem.",
      "The light that leads you off the trail. Not all evidence illuminates; some of it seduces."),
    L("eremita", "隠者", "sorte", "O Eremita", "The Hermit",
      "Recolher-se não é fugir: é audicionar a própria consciência em sessão fechada.",
      "Withdrawing is not fleeing: it is hearing one's own conscience in closed session."),
    L("fudo-da-balanca", "不動の天秤", "sorte", "Fudō da Balança", "Fudō of the Scales",
      "O Imóvel segura o fogo numa mão e a medida na outra. A justiça não treme.",
      "The Immovable One holds fire in one hand and measure in the other. Justice does not tremble."),
    L("miko-vendada", "目隠し巫女", "sorte", "A Miko Vendada", "The Blindfolded Miko",
      "Vendada como a Justiça, mas o que ela pesa não é a culpa: é a vela contra o crisântemo, o tempo contra a promessa.",
      "Blindfolded like Justice, but what she weighs is not guilt: candle against chrysanthemum, time against promise."),
    L("julgamento-do-tengu", "天狗の裁き", "reves", "O Julgamento do Tengu", "The Tengu's Judgment",
      "O tengu pune a vaidade, não o crime. Há tribunais que julgam quem você pensa que é.",
      "The tengu punishes vanity, not crime. Some courts judge who you think you are."),
    L("espelho-de-enma", "閻魔の鏡", "azar", "O Espelho de Enma", "Enma's Mirror",
      "No espelho do rei dos mortos, sua vida inteira, sem edição. A pior prova é a íntegra.",
      "In the dead king's mirror, your whole life, unedited. The worst evidence is the full record."),
    L("chamas-iguais", "等しき炎", "sorte", "As Chamas Iguais", "The Equal Flames",
      "Duas velas, uma altura. A igualdade não é ausência de fogo: é fogo na mesma medida.",
      "Two candles, one height. Equality is not the absence of fire: it is fire in equal measure."),
    L("testemunhas-de-pedra", "石の証人", "sorte", "As Testemunhas de Pedra", "The Stone Witnesses",
      "Os jizō à beira do caminho não esquecem nada. A memória é a única testemunha que não se intimida.",
      "The roadside jizō forget nothing. Memory is the only witness that cannot be intimidated."),
  ];
})();
